// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package uart_apb4_intf_pkg;

    localparam UART_APB4_INTF_DATA_WIDTH = 32;
    localparam UART_APB4_INTF_MIN_ADDR_WIDTH = 5;
    localparam UART_APB4_INTF_SIZE = 'h14;

    typedef struct packed {
        logic [18:0] _reserved_31_13;
        logic ORE;
        logic [4:0] TXFSPACE;
        logic [4:0] RXFLEVEL;
        logic TXFNF;
        logic RXFNE;
    } uart_apb4_intf__UART_SR__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        uart_apb4_intf__UART_SR__external__fields__in_t rd_data;
    } uart_apb4_intf__UART_SR__external__in_t;

    typedef struct packed {
        logic [23:0] _reserved_31_8;
        logic [7:0] RX_DATA;
    } uart_apb4_intf__UART_RX__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        uart_apb4_intf__UART_RX__external__fields__in_t rd_data;
    } uart_apb4_intf__UART_RX__external__in_t;

    typedef struct {
        logic wr_ack;
    } uart_apb4_intf__UART_TX__external__in_t;

    typedef struct {
        uart_apb4_intf__UART_SR__external__in_t UART_SR;
        uart_apb4_intf__UART_RX__external__in_t UART_RX;
        uart_apb4_intf__UART_TX__external__in_t UART_TX;
    } uart_apb4_intf__in_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } uart_apb4_intf__UART_SR__external__out_t;

    typedef struct {
        logic value;
    } uart_apb4_intf__UART_CR__SB__out_t;

    typedef struct {
        logic value;
    } uart_apb4_intf__UART_CR__OVER8__out_t;

    typedef struct {
        uart_apb4_intf__UART_CR__SB__out_t SB;
        uart_apb4_intf__UART_CR__OVER8__out_t OVER8;
    } uart_apb4_intf__UART_CR__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } uart_apb4_intf__UART_RX__external__out_t;

    typedef struct packed {
        logic [23:0] _reserved_31_8;
        logic [7:0] TX_DATA;
    } uart_apb4_intf__UART_TX__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        uart_apb4_intf__UART_TX__external__fields__out_t wr_data;
        uart_apb4_intf__UART_TX__external__fields__out_t wr_biten;
    } uart_apb4_intf__UART_TX__external__out_t;

    typedef struct {
        logic [3:0] value;
    } uart_apb4_intf__UART_BRR__DIV_FRAC__out_t;

    typedef struct {
        logic [11:0] value;
    } uart_apb4_intf__UART_BRR__DIV_MANT__out_t;

    typedef struct {
        uart_apb4_intf__UART_BRR__DIV_FRAC__out_t DIV_FRAC;
        uart_apb4_intf__UART_BRR__DIV_MANT__out_t DIV_MANT;
    } uart_apb4_intf__UART_BRR__out_t;

    typedef struct {
        uart_apb4_intf__UART_SR__external__out_t UART_SR;
        uart_apb4_intf__UART_CR__out_t UART_CR;
        uart_apb4_intf__UART_RX__external__out_t UART_RX;
        uart_apb4_intf__UART_TX__external__out_t UART_TX;
        uart_apb4_intf__UART_BRR__out_t UART_BRR;
    } uart_apb4_intf__out_t;
endpackage
