// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module uart_apb4_intf (
        input wire clk,
        input wire rst,

        apb4_intf.slave s_apb,

        input uart_apb4_intf_pkg::uart_apb4_intf__in_t hwif_in,
        output uart_apb4_intf_pkg::uart_apb4_intf__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [4:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    `ifndef SYNTHESIS
        initial begin
            assert_bad_addr_width: assert($bits(s_apb.PADDR) >= uart_apb4_intf_pkg::UART_APB4_INTF_MIN_ADDR_WIDTH)
                else $error("Interface address width of %0d is too small. Shall be at least %0d bits", $bits(s_apb.PADDR), uart_apb4_intf_pkg::UART_APB4_INTF_MIN_ADDR_WIDTH);
            assert_bad_data_width: assert($bits(s_apb.PWDATA) == uart_apb4_intf_pkg::UART_APB4_INTF_DATA_WIDTH)
                else $error("Interface data width of %0d is incorrect. Shall be %0d bits", $bits(s_apb.PWDATA), uart_apb4_intf_pkg::UART_APB4_INTF_DATA_WIDTH);
        end
    `endif

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb.PSEL) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb.PWRITE;
                    cpuif_addr <= {s_apb.PADDR[4:2], 2'b0};
                    cpuif_wr_data <= s_apb.PWDATA;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb.PSTRB[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb.PREADY = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb.PRDATA = cpuif_rd_data;
    assign s_apb.PSLVERR = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk) begin
        if(rst) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic UART_SR;
        logic UART_CR;
        logic UART_RX;
        logic UART_TX;
        logic UART_BRR;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_strb_is_external;

    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        automatic logic is_external;
        is_external = '0;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.UART_SR = cpuif_req_masked & (cpuif_addr == 5'h0) & !cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 5'h0) & !cpuif_req_is_wr;
        decoded_reg_strb.UART_CR = cpuif_req_masked & (cpuif_addr == 5'h4);
        decoded_reg_strb.UART_RX = cpuif_req_masked & (cpuif_addr == 5'h8) & !cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 5'h8) & !cpuif_req_is_wr;
        decoded_reg_strb.UART_TX = cpuif_req_masked & (cpuif_addr == 5'hc) & cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 5'hc) & cpuif_req_is_wr;
        decoded_reg_strb.UART_BRR = cpuif_req_masked & (cpuif_addr == 5'h10);
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } SB;
            struct {
                logic next;
                logic load_next;
            } OVER8;
        } UART_CR;
        struct {
            struct {
                logic [3:0] next;
                logic load_next;
            } DIV_FRAC;
            struct {
                logic [11:0] next;
                logic load_next;
            } DIV_MANT;
        } UART_BRR;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } SB;
            struct {
                logic value;
            } OVER8;
        } UART_CR;
        struct {
            struct {
                logic [3:0] value;
            } DIV_FRAC;
            struct {
                logic [11:0] value;
            } DIV_MANT;
        } UART_BRR;
    } field_storage_t;
    field_storage_t field_storage;

    // External register: uart_apb4_intf.UART_SR

    assign hwif_out.UART_SR.req = !decoded_req_is_wr ? decoded_reg_strb.UART_SR : '0;
    assign hwif_out.UART_SR.req_is_wr = decoded_req_is_wr;
    // Field: uart_apb4_intf.UART_CR.SB
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_CR.SB.value;
        load_next_c = '0;
        if(decoded_reg_strb.UART_CR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_CR.SB.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.UART_CR.SB.next = next_c;
        field_combo.UART_CR.SB.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_CR.SB.value <= 1'h0;
        end else begin
            if(field_combo.UART_CR.SB.load_next) begin
                field_storage.UART_CR.SB.value <= field_combo.UART_CR.SB.next;
            end
        end
    end
    assign hwif_out.UART_CR.SB.value = field_storage.UART_CR.SB.value;
    // Field: uart_apb4_intf.UART_CR.OVER8
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_CR.OVER8.value;
        load_next_c = '0;
        if(decoded_reg_strb.UART_CR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_CR.OVER8.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.UART_CR.OVER8.next = next_c;
        field_combo.UART_CR.OVER8.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_CR.OVER8.value <= 1'h0;
        end else begin
            if(field_combo.UART_CR.OVER8.load_next) begin
                field_storage.UART_CR.OVER8.value <= field_combo.UART_CR.OVER8.next;
            end
        end
    end
    assign hwif_out.UART_CR.OVER8.value = field_storage.UART_CR.OVER8.value;
    // External register: uart_apb4_intf.UART_RX

    assign hwif_out.UART_RX.req = !decoded_req_is_wr ? decoded_reg_strb.UART_RX : '0;
    assign hwif_out.UART_RX.req_is_wr = decoded_req_is_wr;
    // External register: uart_apb4_intf.UART_TX

    assign hwif_out.UART_TX.req = decoded_req_is_wr ? decoded_reg_strb.UART_TX : '0;
    assign hwif_out.UART_TX.req_is_wr = decoded_req_is_wr;
    assign hwif_out.UART_TX.wr_data = decoded_wr_data;
    assign hwif_out.UART_TX.wr_biten = decoded_wr_biten;
    // Field: uart_apb4_intf.UART_BRR.DIV_FRAC
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_BRR.DIV_FRAC.value;
        load_next_c = '0;
        if(decoded_reg_strb.UART_BRR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_BRR.DIV_FRAC.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.UART_BRR.DIV_FRAC.next = next_c;
        field_combo.UART_BRR.DIV_FRAC.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_BRR.DIV_FRAC.value <= 4'h0;
        end else begin
            if(field_combo.UART_BRR.DIV_FRAC.load_next) begin
                field_storage.UART_BRR.DIV_FRAC.value <= field_combo.UART_BRR.DIV_FRAC.next;
            end
        end
    end
    assign hwif_out.UART_BRR.DIV_FRAC.value = field_storage.UART_BRR.DIV_FRAC.value;
    // Field: uart_apb4_intf.UART_BRR.DIV_MANT
    always_comb begin
        automatic logic [11:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.UART_BRR.DIV_MANT.value;
        load_next_c = '0;
        if(decoded_reg_strb.UART_BRR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.UART_BRR.DIV_MANT.value & ~decoded_wr_biten[15:4]) | (decoded_wr_data[15:4] & decoded_wr_biten[15:4]);
            load_next_c = '1;
        end
        field_combo.UART_BRR.DIV_MANT.next = next_c;
        field_combo.UART_BRR.DIV_MANT.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.UART_BRR.DIV_MANT.value <= 12'h0;
        end else begin
            if(field_combo.UART_BRR.DIV_MANT.load_next) begin
                field_storage.UART_BRR.DIV_MANT.value <= field_combo.UART_BRR.DIV_MANT.next;
            end
        end
    end
    assign hwif_out.UART_BRR.DIV_MANT.value = field_storage.UART_BRR.DIV_MANT.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in.UART_TX.wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in.UART_SR.rd_ack;
        rd_ack |= hwif_in.UART_RX.rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[4];
    assign readback_array[0] = hwif_in.UART_SR.rd_ack ? hwif_in.UART_SR.rd_data : '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.UART_CR && !decoded_req_is_wr) ? field_storage.UART_CR.SB.value : '0;
    assign readback_array[1][1:1] = (decoded_reg_strb.UART_CR && !decoded_req_is_wr) ? field_storage.UART_CR.OVER8.value : '0;
    assign readback_array[1][31:2] = '0;
    assign readback_array[2] = hwif_in.UART_RX.rd_ack ? hwif_in.UART_RX.rd_data : '0;
    assign readback_array[3][3:0] = (decoded_reg_strb.UART_BRR && !decoded_req_is_wr) ? field_storage.UART_BRR.DIV_FRAC.value : '0;
    assign readback_array[3][15:4] = (decoded_reg_strb.UART_BRR && !decoded_req_is_wr) ? field_storage.UART_BRR.DIV_MANT.value : '0;
    assign readback_array[3][31:16] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<4; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
