
// This file was autogenerated by PeakRDL-uvm
package uart_apb4_intf_uvm;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - uart_apb4_intf::UART_SR
    class uart_apb4_intf__UART_SR extends uvm_reg;
        rand uvm_reg_field RXFNE;
        rand uvm_reg_field TXFNF;
        rand uvm_reg_field RXFLEVEL;
        rand uvm_reg_field TXFSPACE;

        function new(string name = "uart_apb4_intf__UART_SR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.RXFNE = new("RXFNE");
            this.RXFNE.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.TXFNF = new("TXFNF");
            this.TXFNF.configure(this, 1, 1, "RO", 1, 'h1, 1, 1, 0);
            this.RXFLEVEL = new("RXFLEVEL");
            this.RXFLEVEL.configure(this, 5, 2, "RO", 1, 'h0, 1, 1, 0);
            this.TXFSPACE = new("TXFSPACE");
            this.TXFSPACE.configure(this, 5, 7, "RO", 1, 'h10, 1, 1, 0);
        endfunction : build
    endclass : uart_apb4_intf__UART_SR

    // reg - uart_apb4_intf::UART_CR
    class uart_apb4_intf__UART_CR extends uvm_reg;
        rand uvm_reg_field SB;
        rand uvm_reg_field OVER8;

        function new(string name = "uart_apb4_intf__UART_CR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.SB = new("SB");
            this.SB.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.OVER8 = new("OVER8");
            this.OVER8.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : uart_apb4_intf__UART_CR

    // reg - uart_apb4_intf::UART_RX
    class uart_apb4_intf__UART_RX extends uvm_reg;
        rand uvm_reg_field RX_DATA;

        function new(string name = "uart_apb4_intf__UART_RX");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.RX_DATA = new("RX_DATA");
            this.RX_DATA.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : uart_apb4_intf__UART_RX

    // reg - uart_apb4_intf::UART_TX
    class uart_apb4_intf__UART_TX extends uvm_reg;
        rand uvm_reg_field TX_DATA;

        function new(string name = "uart_apb4_intf__UART_TX");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.TX_DATA = new("TX_DATA");
            this.TX_DATA.configure(this, 8, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : uart_apb4_intf__UART_TX

    // reg - uart_apb4_intf::UART_BRR
    class uart_apb4_intf__UART_BRR extends uvm_reg;
        rand uvm_reg_field DIV_FRAC;
        rand uvm_reg_field DIV_MANT;

        function new(string name = "uart_apb4_intf__UART_BRR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.DIV_FRAC = new("DIV_FRAC");
            this.DIV_FRAC.configure(this, 4, 0, "RW", 0, 'h0, 1, 1, 0);
            this.DIV_MANT = new("DIV_MANT");
            this.DIV_MANT.configure(this, 12, 4, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : uart_apb4_intf__UART_BRR

    // addrmap - uart_apb4_intf
    class uart_apb4_intf extends uvm_reg_block;
        rand uart_apb4_intf__UART_SR UART_SR;
        rand uart_apb4_intf__UART_CR UART_CR;
        rand uart_apb4_intf__UART_RX UART_RX;
        rand uart_apb4_intf__UART_TX UART_TX;
        rand uart_apb4_intf__UART_BRR UART_BRR;

        function new(string name = "uart_apb4_intf");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.UART_SR = new("UART_SR");
            this.UART_SR.configure(this);

            this.UART_SR.build();
            this.default_map.add_reg(this.UART_SR, 'h0);
            this.UART_CR = new("UART_CR");
            this.UART_CR.configure(this);

            this.UART_CR.build();
            this.default_map.add_reg(this.UART_CR, 'h4);
            this.UART_RX = new("UART_RX");
            this.UART_RX.configure(this);

            this.UART_RX.build();
            this.default_map.add_reg(this.UART_RX, 'h8);
            this.UART_TX = new("UART_TX");
            this.UART_TX.configure(this);

            this.UART_TX.build();
            this.default_map.add_reg(this.UART_TX, 'hc);
            this.UART_BRR = new("UART_BRR");
            this.UART_BRR.configure(this);

            this.UART_BRR.build();
            this.default_map.add_reg(this.UART_BRR, 'h10);
        endfunction : build
    endclass : uart_apb4_intf

endpackage: uart_apb4_intf_uvm
