// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef UART_APB4_INTF_H
#define UART_APB4_INTF_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - uart_apb4_intf::UART_SR
#define UART_APB4_INTF__UART_SR__RXFNE_bm 0x1
#define UART_APB4_INTF__UART_SR__RXFNE_bp 0
#define UART_APB4_INTF__UART_SR__RXFNE_bw 1
#define UART_APB4_INTF__UART_SR__RXFNE_reset 0x0
#define UART_APB4_INTF__UART_SR__TXFNF_bm 0x2
#define UART_APB4_INTF__UART_SR__TXFNF_bp 1
#define UART_APB4_INTF__UART_SR__TXFNF_bw 1
#define UART_APB4_INTF__UART_SR__TXFNF_reset 0x1
#define UART_APB4_INTF__UART_SR__RXFLEVEL_bm 0x7c
#define UART_APB4_INTF__UART_SR__RXFLEVEL_bp 2
#define UART_APB4_INTF__UART_SR__RXFLEVEL_bw 5
#define UART_APB4_INTF__UART_SR__RXFLEVEL_reset 0x0
#define UART_APB4_INTF__UART_SR__TXFSPACE_bm 0xf80
#define UART_APB4_INTF__UART_SR__TXFSPACE_bp 7
#define UART_APB4_INTF__UART_SR__TXFSPACE_bw 5
#define UART_APB4_INTF__UART_SR__TXFSPACE_reset 0x10
#define UART_APB4_INTF__UART_SR__ORE_bm 0x1000
#define UART_APB4_INTF__UART_SR__ORE_bp 12
#define UART_APB4_INTF__UART_SR__ORE_bw 1
#define UART_APB4_INTF__UART_SR__ORE_reset 0x0

// Reg - uart_apb4_intf::UART_CR
#define UART_APB4_INTF__UART_CR__SB_bm 0x1
#define UART_APB4_INTF__UART_CR__SB_bp 0
#define UART_APB4_INTF__UART_CR__SB_bw 1
#define UART_APB4_INTF__UART_CR__SB_reset 0x0
#define UART_APB4_INTF__UART_CR__OVER8_bm 0x2
#define UART_APB4_INTF__UART_CR__OVER8_bp 1
#define UART_APB4_INTF__UART_CR__OVER8_bw 1
#define UART_APB4_INTF__UART_CR__OVER8_reset 0x0

// Reg - uart_apb4_intf::UART_RX
#define UART_APB4_INTF__UART_RX__RX_DATA_bm 0xff
#define UART_APB4_INTF__UART_RX__RX_DATA_bp 0
#define UART_APB4_INTF__UART_RX__RX_DATA_bw 8
#define UART_APB4_INTF__UART_RX__RX_DATA_reset 0x0

// Reg - uart_apb4_intf::UART_TX
#define UART_APB4_INTF__UART_TX__TX_DATA_bm 0xff
#define UART_APB4_INTF__UART_TX__TX_DATA_bp 0
#define UART_APB4_INTF__UART_TX__TX_DATA_bw 8
#define UART_APB4_INTF__UART_TX__TX_DATA_reset 0x0

// Reg - uart_apb4_intf::UART_BRR
#define UART_APB4_INTF__UART_BRR__DIV_FRAC_bm 0xf
#define UART_APB4_INTF__UART_BRR__DIV_FRAC_bp 0
#define UART_APB4_INTF__UART_BRR__DIV_FRAC_bw 4
#define UART_APB4_INTF__UART_BRR__DIV_FRAC_reset 0x0
#define UART_APB4_INTF__UART_BRR__DIV_MANT_bm 0xfff0
#define UART_APB4_INTF__UART_BRR__DIV_MANT_bp 4
#define UART_APB4_INTF__UART_BRR__DIV_MANT_bw 12
#define UART_APB4_INTF__UART_BRR__DIV_MANT_reset 0x0

// Addrmap - uart_apb4_intf
typedef struct __attribute__ ((__packed__)) {
    uint32_t UART_SR;
    uint32_t UART_CR;
    uint32_t UART_RX;
    uint32_t UART_TX;
    uint32_t UART_BRR;
} uart_apb4_intf_t;


static_assert(sizeof(uart_apb4_intf_t) == 0x14, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* UART_APB4_INTF_H */
